# conf/config.yaml
defaults:
  - override hydra/sweeper: optuna
params:
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 100
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_weight: 1
  gamma: 0.0
  reg_alpha: 0.0
  reg_lambda: 1.0

hydra:
  sweeper:
    direction: maximize
    study_name: xgb_sweep
    n_trials: 30
    params:
      params.learning_rate: float(0.001, 0.3)
      params.max_depth: int(3, 20)    
      params.n_estimators: int(50, 1000)    
      params.subsample: float(0.5, 1.0)     
      params.colsample_bytree: float(0.5, 1.0)     
      params.min_child_weight: int(1, 10)          
      params.gamma: float(0.0, 5.0)                
      params.reg_alpha: float(0.0, 5.0) 
      params.reg_lambda: float(0.0, 5.0)
      