params:
  learning_rate: 0.1
  max_depth: 6
  n_estimators: 100
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_weight: 5
  gamma: 0.1
  reg_alpha: 0.1
  reg_lambda: 0.1

embeddingmodel: 'bert'
finetune: False
gptdatapath: '/home/miza/Magisterka/src/data/annotations/gpt_generated_data.csv'
datapath: '/home/miza/Magisterka/src/data/annotations/annotations.csv'
defaults:
  - params: params_best_8classes
  - override hydra/sweeper: optuna


hydra:
  sweeper:
    direction: maximize
    study_name: xgb_sweep
    n_trials: 50
    params:
      params.learning_rate: float(0.001, 0.3)
      params.max_depth: int(3, 20)    
      params.n_estimators: int(50, 1000)    
      params.subsample: float(0.5, 1.0)     
      params.colsample_bytree: float(0.5, 1.0)     
      params.min_child_weight: int(1, 10)          
      params.gamma: float(0.0, 5.0)                
      params.reg_alpha: float(0.0, 5.0) 
      params.reg_lambda: float(0.0, 5.0)
      